### ISSUE TITLE
cannot connect to container based on latest dockerhub build of reporter 

### ISSUE THREAD

**Issue by mxndrwgrdnr** [opentraffic/reporter#90] opened 2017-08-04 19:34 UTC
Opening an issue per our conversation today @kevinkreiser. 

All of my HTTP requests to a running instance of the newest Reporter image hung, not failing or timing out but never completing.

Similarly, Kevin was unable to `docker exec -it` into a Reporter instance based on the same latest image. 

Reverting back to older versions of the container fix the problem, so something must be going on with the latest build, aka `opentraffic/reporter:4c206e126c040fa98039611d91ccccd0ee618e09` or `opentraffic/reporter:latest`. Images starting at `opentraffic/reporter: c813127d3d41bf5a11b5a2f8fc38653f8454f60a` and earlier all seem to work fine.

**Comment by kevinkreiser** [comment] 2017-08-09 15:39
turns out i was not able to reproduce this. i thought i was but really i was messing up the command.

so even with the latest i can confirm everything is working. heres how to do it with just some commands:

```bash
docker network create --driver bridge opentraffic
docker run --net opentraffic -p 8002:8002 --name reporter-py -v /data/valhalla:/data/valhalla opentraffic/reporter:latest
```

here's what a valid docker compose file looks like so you can just do `docker-compose up`:

```yml
version: "2"
services:

  reporter:
    image: opentraffic/reporter:latest
    network_mode: "bridge"
    ports:
      - "8003:8003"
    volumes:
      - ${VALHALLA_DOCKER_DATAPATH}:/data/valhalla
    environment:
      - MATCHER_LISTEN_PORT=8003
    container_name: reporter
```

notice the `newtwork_mode` set to `bridge` instead of `network` set to a name. having network set to a name doesnt work and always gives an error of `ERROR: Service "reporter" uses an undefined network "opentraffic"`

**Comment by kevinkreiser** [comment] 2017-08-09 15:39
@drewda can you confirm this so we can close the issue

**Comment by drewda** [comment] 2017-08-09 15:40
@kevinkreiser sure, I'll try rerunning the Docker/notebook rig locally.

**Comment by mxndrwgrdnr** [comment] 2017-08-09 18:28
@kevinkreiser can you confirm you can communicate with the reporter service remotely, i.e. HTTP requests, a-la the snippet I gave you last week?

@drewda let me know if you have any problems getting the rig up and running in order to test.

I'm not sure I'll have time to test this myself until later tonight or tomorrow.

**Comment by kevinkreiser** [comment] 2017-08-09 18:46
@mxndrwgrdnr yes i can confirm it, curl or browser work perfectly. the snippet i havent tried but... i just found a bug where certain routes will cause the reporter to hang, so i'll debug that first and then we can see if it will answer your specific route

**Comment by drewda** [comment] 2017-08-10 22:50
I've tested locally and _think_ this may be an issue elsewhere in the Reporter Quality Testing Rig Notebook, rather than in the Reporter Docker container.

Let me share my testing steps here, in case @mxndrwgrdnr notices anything I've skipped.

1. I got the local Docker rig working; had to change one version number for the Valhalla image (https://github.com/opentraffic/reporter-quality-testing-rig/pull/11)
2. Opened the http://localhost:8888/notebooks/notebooks/validation.ipynb# notebook
3. Run steps up to and including the matching:

![2017-08-10_15-30-56](https://user-images.githubusercontent.com/212369/29194957-f2c7d7d0-7de0-11e7-8fda-2349b0bb61af.png)

4. In the Docker container logs, I also made sure to look for the Reporter container`/report` endpoint being called. Here's one of the requests, which I was also able to reproduce from my shell (outside Docker):

```sh
➜  reporter-quality-testing-rig git:(docker-updates) ✗ curl "http://localhost:8003/report?json=%7B%22match_options%22:%7B%22turn_penalty_factor%22:500,%22sigma_z%22:4.07,%22breakage_distance%22:2000,%22beta%22:3,%22gps_accuracy%22:41.12,%22mode%22:%22auto%22%7D,%22shape_match%22:%22map_snap%22,%22uuid%22:%22999999%22,%22trace%22:%5B%7B%22lat%22:37.787622,%22lon%22:-122.413731,%22time%22:1502316981%7D,%7B%22lat%22:37.785312,%22lon%22:-122.412453,%22time%22:1502317011%7D,%7B%22lat%22:37.782984,%22lon%22:-122.413868,%22time%22:1502317041%7D,%7B%22lat%22:37.782492,%22lon%22:-122.417329,%22time%22:1502317071%7D,%7B%22lat%22:37.781888,%22lon%22:-122.420411,%22time%22:1502317101%7D,%7B%22lat%22:37.779156,%22lon%22:-122.420101,%22time%22:1502317131%7D,%7B%22lat%22:37.776297,%22lon%22:-122.41942,%22time%22:1502317161%7D,%7B%22lat%22:37.773902,%22lon%22:-122.421035,%22time%22:1502317191%7D,%7B%22lat%22:37.771365,%22lon%22:-122.422499,%22time%22:1502317221%7D,%7B%22lat%22:37.768707,%22lon%22:-122.422049,%22time%22:1502317251%7D,%7B%22lat%22:37.76581,%22lon%22:-122.421886,%22time%22:1502317281%7D,%7B%22lat%22:37.763091,%22lon%22:-122.421379,%22time%22:1502317311%7D,%7B%22lat%22:37.760302,%22lon%22:-122.421027,%22time%22:1502317341%7D,%7B%22lat%22:37.757621,%22lon%22:-122.421186,%22time%22:1502317371%7D,%7B%22lat%22:37.756069,%22lon%22:-122.421901,%22time%22:1502317401%7D,%7B%22lat%22:37.756142,%22lon%22:-122.422682,%22time%22:1502317406%7D%5D%7D" | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8614  100  8614    0     0   190k      0 --:--:-- --:--:-- --:--:--  191k
{
  "datastore": {
    "mode": "auto",
    "reports": [
      {
        "t0": 1502316984.219,
        "t1": 1502316994.507,
        "length": 104,
        "queue_length": 0,
        "next_id": 486405412489,
        "id": 297863059081
      },
...
```

Looks successful, both in terms of 200 response code and the contents (which I've cut off).

The one thing that I am noticed is that the Jupyter Notebook cell that runs `matchDf, _ = val.get_route_metrics(routeList, sampleRates, noiseLevels, saveResults=False)` doesn't seem to mark as complete. The kernel stays busy and the cell doesn't get a number to indicate completion:

![2017-08-10_15-45-24](https://user-images.githubusercontent.com/212369/29195363-f9456b34-7de2-11e7-910a-f30e6e4e211e.png)

Not sure what isn't completing... but at least to my naive eyes, it looks like Reporter is successfully acting on the `/report` requests.

**Comment by drewda** [comment] 2017-08-11 20:07
Good news: When running the very latest version of Reporter image (`07e14cdc91ae7fa2f7361b25e8ec1b1c2d1c1cc1`), this cell now successfully completes.

Confusing news: looks like `get_route_metrics(routeList, sampleRates, noiseLevels, saveResults=False)` returns three elements, rather than 2.

Going to close this issue now, since Reporter is successfully running. Will follow up over on the rig repo about handling the different (?) output.

**Closed as completed by drewda** 2017-08-11 20:07 UTC
Labels: bug

**Comment by mxndrwgrdnr** [comment] 2017-08-14 20:15
Can confirm the issue is solved. Will follow up with @drewda offline re: the confusing news above.
